# Generated by Django 2.2.3 on 2019-07-08 21:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(help_text='Year of release', verbose_name='Year of release')),
                ('released', models.DateField(help_text='Release date', verbose_name='Release date')),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('actors', models.TextField()),
                ('plot', models.TextField(max_length=1000)),
                ('language', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('metascore', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Metacritic score')),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='IMDb rating')),
                ('imdb_votes', models.IntegerField(verbose_name='IMDb votes')),
                ('imdb_id', models.CharField(max_length=20)),
                ('dvd', models.DateField(verbose_name='DVD release date')),
                ('box_office', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.Movie')),
            ],
        ),
    ]
